############################
## Navbar
############################

main:
- name: Accueil
  url: /
  weight: 10
- name: Ã€ propos
  url: /about/
  weight: 20
- name: Projets
  url: /projets/
  weight: 30
- name: Apprentissages
  url: /apprentissages/
  weight: 40
